pause:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          domain: cover

resume:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          domain: cover

pause_all:

resume_all:

set_scenario:
  fields:
    scenario:
      required: true
      example: "everyday"
      selector:
        text:

export_config:
  fields:
    path:
      default: /config/cover_automatic/cover_automatic_backup.yaml
      selector:
        text:

import_config:
  fields:
    path:
      required: true
      selector:
        text:
